// Produce interface model
export interface Product {
    productUpdatedAt?: Date;
    productSize?: string[];
    productCategory: string;
    productBrand: string;
    productCreatedAt: Date;

    // Display Data
    productId?: string; // Make productId optional since it will be generated by the database
    productName: string;
    productDescription: string;
    productPrice: number;
    productGender: string;
    productImage: string;
    productAmountSold: number;
    productColorVarietyDetail?: ProductColorVarietyDetail[];
}

export interface ProductColorVarietyDetail {
    productColor: string;
    productSize: string[];
    productStock: number[];
}

export interface ProductInCart {
    productId?: string;
    productName: string;
    productDescription: string;
    productPrice: number;
    productGender: string;
    productImage: string;
    productAmountSold: number;
    productColor: string | null;
    productSize: string | null;
}

export interface ProductDisplay {
    productId?: string;
    productName: string;
    productDescription: string;
    productPrice: number;
    productGender: string;
    productImage: string;
    productAmountSold: number;
    productColorVarietyDetail?: ProductColorVarietyDetail[];
}